"""Generate ruleset/INDEX.md from rules/*.yaml."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RULES = ROOT / "ruleset" / "rules"
INDEX = ROOT / "ruleset" / "INDEX.md"

try:
    import yaml  # type: ignore
except ImportError:
    yaml = None


def parse_simple(path: Path) -> list[dict]:
    """Minimal YAML subset parser for our rule files (no nested structures we need)."""
    if yaml is not None:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        return data.get("rules") or []

    rules: list[dict] = []
    cur: dict | None = None
    key: str | None = None
    buf: list[str] = []

    def flush_buf() -> None:
        nonlocal key, buf
        if cur is None or key is None:
            buf = []
            return
        text = " ".join(x.strip() for x in buf).strip()
        if text:
            cur[key] = text
        key = None
        buf = []

    for raw in path.read_text(encoding="utf-8").splitlines():
        if raw.startswith("  - id:"):
            flush_buf()
            if cur:
                rules.append(cur)
            cur = {"id": raw.split(":", 1)[1].strip()}
            continue
        if cur is None:
            continue
        if raw.startswith("    ") and not raw.startswith("     ") and ":" in raw and not raw.strip().startswith("-"):
            flush_buf()
            k, _, rest = raw.strip().partition(":")
            rest = rest.strip()
            if rest == ">" or rest == "|":
                key = k
                buf = []
            elif rest.startswith("[") and rest.endswith("]"):
                cur[k] = rest
            else:
                cur[k] = rest
        elif key is not None and (raw.startswith("      ") or raw.startswith("    ")):
            buf.append(raw)
    flush_buf()
    if cur:
        rules.append(cur)
    return rules


def main() -> None:
    rows: list[tuple[str, str, str, str, str, str]] = []
    for path in sorted(RULES.glob("*.yaml")):
        cat = path.stem
        for r in parse_simple(path):
            title = r.get("title") or ""
            if not title:
                raise SystemExit(f"{path.name}: {r.get('id')} has no title ({r!r})")
            rows.append(
                (
                    r["id"],
                    title,
                    str(r.get("severity") or ""),
                    str(r.get("check") or ""),
                    str(r.get("default") or ""),
                    cat,
                )
            )

    lines = [
        "# Canonical rule index",
        "",
        f"Generated by `python tools/generate_ruleset_index.py`. {len(rows)} rules.",
        "",
        "| ID | Title | Severity | Check | Default | File |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for rid, title, sev, check, default, cat in rows:
        title = title.replace("|", "\\|")
        lines.append(f"| `{rid}` | {title} | {sev} | {check} | {default} | `{cat}.yaml` |")
    INDEX.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {INDEX} ({len(rows)} rules)")


if __name__ == "__main__":
    main()
